### ISSUE TITLE
Skiss för avdelningssida

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/vardgivarwebben#16]
# User story
Som produktägare vill jag se en skiss på en avdelningssida

# Acceptanskriterier

- [ ] Skissen ska visa hur sidan hur sidan ser ut i mobil, tablet och desktop
- [ ] Skissen ska visa hur användaren kommer vidare från avdelningssidan

**Comment by fridabergentoft** [comment]
https://invis.io/KVFH0HECZW5
