### ISSUE TITLE
Som intressent vill jag se en prototyp för området Läkemedelsgenomgångar för att se om det går att gå över till en digital version

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/vardgivarwebben#20]
## Acceptanskriterier
- [x] Prototypen ska visa hur detta ser på mobil, tablet och desktop
- [x] Prototypen ska presentera 
[Läkemedelsfakta 2017.docx](https://github.com/RegionHalland/vardgivarwebben/files/1655258/Lakemedelsfakta.2017.docx)

**Comment by JohannaOlin** [comment]
Ändra så att navigationen ser ut så här
![Läkemedelsgenomgångar.PNG](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/d25b55eb-e467-4d28-b19f-f8cf29f25eb4)

Linda vill gärna att vi skickar ut en klickbar prototyp för test och jag tänker att man kommer in på "startsidan" Läkemedelsgenomgångar och sedan kan klicka sig ner på Verktyg vid läkemedelsgenomgångar särskilda boenden - Läkemedelsfakta och att man sedan kan klicka på en bokstav och sen en post i listan.

På sidan Läkemedelsgenomgångar kan du bara lägga in lite exempeltext. 
På sidan som heter Verktyg vid läkemedelsgenomgångar särskilda boenden så kan du bara lägga lite exempeltext. Får inte begreppet plats i navigationen så skriv Verktyg bara så länge, men låt rubriken på sidan vara Verktyg vid läkemedelsgenomgångar på särskilda boenden.

På sidan Läkemedelsfakta kan du ha exempeltexten, sökrutan och A-Ö listan. Sen kan man klicka på en bokstav och då ser du det som finns på skissen idag.

Klickar du sedan på en post i listan så kan du komma till en av undersidorna till Läkemedelsfakta med text. Om du använder bokstaven D och posten Dentan så ska man hamna under Mun- och tandsjukdomar. Antingen kan du bara lägga in lite lorem lipsum text eller så kopierar du det översta från det avsnittet i pärmen.

**Comment by fridabergentoft** [comment]
https://invis.io/KHFXVMUTSUX
