### ISSUE TITLE
Som produktägare vill jag ha en sida för Vårdgivarwebben

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/vardgivarwebben#23]
## Acceptanskriterier
- [x] När användarna skriver in vardgivare.regionhalland.se så ska de komma till en sida
- [x] Sidan ska kunna visa text
- [x] Det ska finnas en länk till terapirekommendationerna på sidan

**Comment by JohannaOlin** [comment]
@davidohlin Du kan lägga in nedanstående text på sidan. Går det att göra mitt namn klickbart med mailto-länk johanna.olin@regionhalland.se?

## Välkommen till webbplatsen för vårdgivare.
På den här webbplatsen kommer vi att samla information och tjänster för dig som vårdgivare i Halland så att du lättare ska nå det du behöver.
Under våren kommer innehållet efterhand att utökas med nya innehållsområden och någon gång i april kommer en ny startsida att presenteras. Till dess finns länkar till innehållet på webbplatsen för vårdgivare på regionens intranät, extranät och på www.regionhalland.se.

Om du har frågor eller vill vara med och hjälpa oss att testa innehåll och funktioner är du välkommen att höra av dig till Johanna Olin. Vi behöver din hjälp.

**Comment by davidohlin** [comment]
Det går finfint med en länk. Jag fixar det 👍

**Comment by JohannaOlin** [comment]
@regionhallandviktor Kan vi stänga denna?
