### ISSUE TITLE
Som användare vill jag ha en vänstermeny så att jag kan klicka mig ner i strukturen

### ISSUE THREAD

**Issue by sebastiansson** [RegionHalland/vardgivarwebben#3]
# Acceptanskriterier
- [x] Menyn ska endast visa det som ligger **en** nivå under aktuellt val
- [x] Menyn skall fungera på alla skärmar
- [x] Koden ska checkas in i Halland-reposet
- [x] Menyn ska kunna användas på andra webbplatser 

- [ ] WCAG AA skall uppfyllas
_Copied from original issue: RegionHalland/Vardgivarwebben#3_

**Comment by regionhallandviktor** [comment]
Några QA-anmärkningar om tillgänglighet:

(Utgår från sidan http://vg.digitaliseringsbyran.se/behandlingsstod/lakemedel/ [2018-04-04]

- [ ] ul-listan som driver vänsternav behöver ett attribut aria-labelledby. (När man tabbar med talsyntes får man inte kontexten klar för sig)

Det ser ut såhär när det är klart

```
<span class="sidebar-nav__label" id="lämpligt_id">Läkemedel</span>
<ul class="sidebar-nav__sublist" aria-labelledby="lämpligt_id">
```

- [ ] Kontrasten behöver ökas för själva vänsternavigationen gentemot omgivningen - nu är det bara aktuell sida som är tydlig.  I WCAG 2.1 som kommer (i år?) så kommer ökade krav på att gränssnittskomponenter skall ha vettiga kontrastvärden mot omgivningen så vi kunde gärna ge hela menyn bakgrundsfärg. (Vi kan prova med den ljusblå + skarpare färg på borders även om den är väl blek)

**Comment by regionhallandviktor** [comment]
Vad är status på den här? Finns den aktiv på stage-vardgivare ngnstans så man kan kika på den - annars bör den kanske åka tillbaka till backlog?
