### ISSUE TITLE
Länkar - Som redaktör vill jag kunna lägga länkar på en sida

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/vardgivarwebben#30]
## Acceptanskriterier
- [x] Redaktören ska kunna ange en titel för länken som också ska användas som visningsnamn på sidan
- [x] Redaktören ska kunna bestämma i vilken ordning länkarna visas
- [x] Redaktören ska kunna gruppera länkarna
- [x] Redaktören ska kunna ange en rubrik för gruppen av länkar
- [x] Redaktören ska kunna lägga in mer än en grupp med länkar på en sida

**Comment by simpel** [comment]
Vill vi blanda länkar och dokument i samma lista eller är det kanske två separata grejjer?

**Comment by regionhallandviktor** [comment]
Noterade att vi behöver knyta länklistans ul till rubriken med ett "aria-labelledby"-attribut. 
<h3 id="X">Viktiga länkar</h3>
....
<ul aria-labelledby="X">
<li>.... 

Gör vi inte det har man noll kontext och får bara höra att det är en lista med ett visst antal länkar. Att det är en lista som heter "Viktiga länkar" är ju en klart viktig information i sammanhanget.
