### ISSUE TITLE
Nyheter - Som redaktör vill jag kunna skapa nyheter

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/vardgivarwebben#31]
## Acceptanskriterier
- [x] Som redaktör ska jag kunna välja att visa inlägget på en eller flera webbplatser
- [x] Som redaktör ska jag kunna tagga inlägget med vilket område det gäller
- [x] Som administratör ska jag kunna lägga till fler taggningsmöjligheter för inläggen om det behövs
- [x] Som redaktör ska jag kunna skriva in en titel/rubrik för inlägget
- [x] Som redaktör ska jag kunna ange ett url-namn för inlägget
- [x] Som redaktör kan jag ange ett publiceringsdatum för inlägget
- [x] Det ska gå att flytta inläggen till en egen server

**Comment by simpel** [comment]
Vill vi särskilja detta från en blogg tro? eller är det samma sak?
