### ISSUE TITLE
Som besökare vill jag kunna urskilja länkar

### ISSUE THREAD

**Issue by regionhallandviktor** [RegionHalland/vardgivarwebben#41]
## Acceptanskriterier
- [ ] Länkar är tydligt urskiljbara se Stilguiden i wikin

Övrigt: Den nuvarande länkfärgen har bara en kontrast på 2.17:1 vilket gör dem svåra att upptäcka för de med dåligt färgseende eftersom färg är den enda betydelsebäraren.

**Comment by regionhallandviktor** [comment]
Se t.ex. http://stage-vardgivare.regionhalland.se/service-it/it-stod-och-system/lakemedelsdatabas-pillan/ där det idag (16 april 2018) är i princip omöjligt att urskilja länken som inleder texten på sidan.

**Comment by JohannaOlin** [comment]
Jag flyttade denna till terapirekommendationerna så jag stänger denna.
