### ISSUE TITLE
Länkstig - Som besökare vill jag se en länkstig på sidan så att jag kan se var i strukturen sidan befinner sig

### ISSUE THREAD

**Issue by sebastiansson** [RegionHalland/vardgivarwebben#8]
_From @JohannaOlin on January 15, 2018 6:32_

## Acceptanskriterier

- [x] Länkstigen ska börja med Start som leder till startsidan
- [x] Länkstigen ska visa samtliga nivåer fram till och med aktuell sida
- [x] Länkstigen ska vara länkad till respektive sida
- [x] Aktuell sida ska inte vara länkad
- [x] Länkstigen ska kunna visa många nivåer
- [x] Länkstigen ska kunna visas även på tablet, ej på mobil

- [ ] Talsyntes-användare får kontexten förklarad för sig när de tabbar till länkstigen. 

_Copied from original issue: RegionHalland/Vardgivarwebben#8_

**Comment by regionhallandviktor** [comment]
I talsyntes är länkstigen kontextlös. Jag föreslår att vi förtydligar med ett aria-label attribrut. Såhär: <ol aria-label="länkstig"><li>
